artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/rajumavinmar/finger-print-based-blood-group-dataset
  local_data_file: artifacts/data_ingestion/FingerPrint.zip
  unzip_dir: artifacts/data_ingestion
  unzipped_data_dir: artifacts/data_ingestion/FingerPrint



model_training:
  
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/fingerprint_model 
